- Jenkinsfile.yml
Added archive artifacts step to jenkins file to pull the binaries of all-in-one-demo in jenkins
Signed-off-by: Mareddy, Deepthi <deepthix.mareddy@intel.com>
> Update jenkins file to archive the binaries of all-in-one-demo in jenkins

- Jenkinsfile.yml
Replace git clone with checkout scm to fix the checkout issue while building pull request.
Signed-off-by: Mareddy, Deepthi <deepthix.mareddy@intel.com>
> Updated jenkinsfile to fix the checkout issue while building PR

- build/Dockerfile
- build/README.md
- build/build.sh
- build/docker-compose.yml
1. The script is able to build the local copy of source code,
by mounting the local copy into the container and building the mounted local copy.
2. The script is able to build the latest upstream copy,
by cloning and building the upstream in /tmp folder of the container and
finally copying the container/target folder into the mounted local copy.
> Ubuntu Docker Script for Building AIO

- README.md
Signed-off-by: Tom Barnes <thomas.j.barnes@intel.com>
> Update demo readme files with -not for production- note

- Jenkinsfile.yml
Added a new stage Run Smoke test on the latest commit binaries with the
latest binaries of client-sdk and PRI Device
Signed-off-by: Mareddy, Deepthi <depthix.mareddy@intel.com>
> Updated Jenkinsfile to run aio smoketests.

- container/overlay/tomcat/conf/server.xml
- container/overlay/tomcat/conf/web.xml
- container/overlay/tomcat/webapps/ROOT/WEB-INF/web.xml
- container/pom.xml
- services/pom.xml
Signed-off-by: Behera, Tushar Ranjan <tushar.ranjan.behera@intel.com>
> Bump Tomcat version to 9.0.37

- build/build.sh
Fixing AIO Docker Build Script to clone and build OnPrem RV
along with other required SDO components.
> Fixing AIO Docker Build Script.

- README.md
- container/overlay/README.md
Updating the AIO README files to include the new OnPrem-RV
integration information and to reflect the changes in this release.
> Updates to README.md

- container/overlay/tomcat/conf/catalina.properties
- container/pom.xml
- pom.xml
- services/pom.xml
AIO version roll to 1.9 release from 1.9-SNAPSHOT.
> Roll Version to 1.9

- README.md
- build/README.md
- container/overlay/README.md
Fixed the target artifact location in build/README.md file.
While at it, fixed a few styling issues.
Signed-off-by: Behera, Tushar Ranjan <tushar.ranjan.behera@intel.com>
> README: Few minor fixes

- build/docker-compose.yml
- container/overlay/docker-compose.yaml
Adding Security enhancements to both builder and demo docker script
as per the CIS security benchmark recommendations.
> Security enhancements to Docker Scripts

- container/overlay/tomcat/webapps/api/WEB-INF/web.xml
- container/pom.xml
- services/pom.xml
- services/src/main/java/org/sdo/demo/AioDb.java
- services/src/main/java/org/sdo/demo/AioInfoServlet.java
Implemented a REST end-point to for serving additional device information from
all-in-one-demo. The REST end-point extracts following information from
the database.
- SerialNumber
- Timestamp for DI
- Device UUID
Signed-off-by: Sajadpour, NimaX <nimax.sajadpour@intel.com>
Signed-off-by: Behera, Tushar Ranjan <tushar.ranjan.behera@intel.com>
> Implements a REST endpoint for Serving Device Info

- services/pom.xml
- services/src/main/java/org/sdo/demo/AioApiServlet.java
- services/src/main/java/org/sdo/demo/AioContextListener.java
- services/src/main/java/org/sdo/demo/AioDb.java
- services/src/main/java/org/sdo/demo/DiListener.java
- services/src/main/java/org/sdo/demo/RelayServlet.java
- Implements new exception handling structures.
- Adding proper exception handling messages.
- Removing all printStackTrace calls.
- Switching from console printing to Slf4j logging.
> Adding Exception Handling Structures

- services/pom.xml
- services/src/main/java/org/sdo/demo/AioDb.java
- services/src/test/java/org/sdo/demo/AioApiServletTest.java
- services/src/test/java/org/sdo/demo/AioDbTest.java
1. UT for AioApiServlet class.
2. UT for AioDb class.
> Adding unit tests to AIO-service

- container/overlay/tomcat/conf/catalina.properties
- services/src/main/java/org/sdo/demo/AioApiServlet.java
- services/src/main/java/org/sdo/demo/AioFilesServlet.java
Adding sanity check on the file name and path.
> Input validation for REST calls

- services/src/main/java/org/sdo/demo/AioApiServlet.java
- services/src/main/java/org/sdo/demo/AioContextListener.java
- services/src/main/java/org/sdo/demo/AioDb.java
- services/src/main/java/org/sdo/demo/AioFilesServlet.java
- services/src/main/java/org/sdo/demo/AioInfoServlet.java
- services/src/main/java/org/sdo/demo/RelayServlet.java
- services/src/test/java/org/sdo/demo/AioApiServletTest.java
Changes based on Initial PSEC comments.
> PSEC review

- container/overlay/README.md
Updating README file to include v1/deviceinfo/{seconds}
REST endpoint information.
> Updating README.md

- container/overlay/tomcat/conf/catalina.properties
Adding Credential security disclaimer in catalina.properties file.
> Adding Credential Security Disclaimer

- container/overlay/README.md
- services/src/main/java/org/sdo/demo/AioApiServlet.java
- services/src/main/java/org/sdo/demo/AioFilesServlet.java
Fixing the REST endpoint to return 406 NOT ACCEPTABLE status
if the uploaded file name/path is invalid.
> Fixing the REST endpoint

- services/src/main/java/org/sdo/demo/AioApiServlet.java
> Adding GUID validation for REST endpoints

- build/README.md
Updating Ubuntu version in docker build README.
> Updating Ubuntu version in docker build README

- container/pom.xml
- pom.xml
- services/pom.xml
AIO version roll to 1.10 release from 1.10-SNAPSHOT.
> Roll version to 1.10

- Jenkinsfile.yml
- container/overlay/docker-compose.yaml
- container/overlay/tomcat/conf/catalina.properties
- container/pom.xml
- pom.xml
- services/pom.xml
Roll version for 1.10.1 development.
> Roll version for 1.10.1 development

- container/overlay/Dockerfile
- container/overlay/tomcat/conf/server.xml
Fixing the Typo error in Server.xml file.
> Fixing Typo error in Server.xml file

- build/Dockerfile
- build/build.sh
- container/pom.xml
- pom.xml
- services/pom.xml
Version roll-over to 1.10.1 Release.
> Version roll-over to 1.10.1 Release

- container/overlay/Dockerfile
- container/overlay/dockerfiles/Dockerfile-rendezvous
Signed-off-by: Behera, Tushar Ranjan <tushar.ranjan.behera@intel.com>
> Update docker containers with latest packages

- container/overlay/docker-compose.yaml
- container/overlay/tomcat/conf/catalina.properties
- container/pom.xml
- pom.xml
- services/pom.xml
Version rollover for 1.10.3 Development.
> Version rollover for 1.10.3 Development

- container/overlay/docker-compose.yaml
- container/overlay/tomcat/conf/catalina.properties
- container/pom.xml
- pom.xml
- services/pom.xml
Roll version to 1.10.3 RELEASE.
> Roll version to 1.10.3 RELEASE

- container/overlay/docker-compose.yaml
- container/overlay/tomcat/conf/catalina.properties
- container/pom.xml
- pom.xml
- services/pom.xml
Version rollover to 1.10.4-SNAPSHOT.
> Version rollover to 1.10.4-SNAPSHOT

- container/overlay/docker-compose.yaml
- container/overlay/tomcat/conf/catalina.properties
- container/pom.xml
- pom.xml
- services/pom.xml
Version rollover to 1.10.4 Release.
> Version rollover to 1.10.4 Release

- container/overlay/docker-compose.yaml
- container/overlay/tomcat/conf/catalina.properties
- container/pom.xml
- pom.xml
- services/pom.xml
Version rollover to 1.10.5-SNAPSHOT.
> Version rollover to 1.10.5-SNAPSHOT

- build/Dockerfile
- container/overlay/Dockerfile
Installing haveged libraries in Docker container.
> Installing haveged libraries in Docker container

- services/pom.xml
Upgrading spring-core version from 5.3.13 to 5.3.15.
> Upgrading spring-core version from 5.3.13 to 5.3.15

- container/overlay/docker-compose.yaml
- container/overlay/tomcat/conf/catalina.properties
- container/pom.xml
- pom.xml
- services/pom.xml
Version rollover to 1.10.6-SNAPSHOT.
> Version rollover to 1.10.6-SNAPSHOT

- container/pom.xml
- services/pom.xml
Upgrading dependencies to latest version.
> Upgrading dependencies to latest version

- container/overlay/docker-compose.yaml
- container/overlay/tomcat/conf/catalina.properties
- container/pom.xml
- pom.xml
- services/pom.xml
Version rollover to 1.10.6 Release.
> Version rollover to 1.10.6 Release

- container/overlay/docker-compose.yaml
- container/overlay/tomcat/conf/catalina.properties
- container/pom.xml
- pom.xml
- services/pom.xml
Version rollover to 1.10.7-SNAPSHOT.
> Version rollover to 1.10.7-SNAPSHOT

- Jenkinsfile.yml
- container/pom.xml
- services/pom.xml
Upgrading dependencies to the latest version.
> Upgrading dependencies to the latest version

- README.md
- container/overlay/docker-compose.yaml
- container/overlay/tomcat/conf/catalina.properties
- container/pom.xml
- pom.xml
- services/pom.xml
Version rollover to 1.10.7 Release.
> Version rollover to 1.10.7 Release

- container/overlay/docker-compose.yaml
- container/overlay/tomcat/conf/catalina.properties
- container/pom.xml
- pom.xml
- services/pom.xml
Version rollover to 1.10.8 SNAPSHOT.
> Version rollover to 1.10.8 SNAPSHOT

- README.md
- build/README.md
- container/overlay/README.md
Updating Docker version in README.
> Updating Docker version in README

- container/overlay/docker-compose.yaml
- container/overlay/tomcat/conf/catalina.properties
- container/pom.xml
- pom.xml
- services/pom.xml
Version rollover to 1.10.8 Release.
> Version rollover to 1.10.8 Release

- container/pom.xml
> Upgrading commons-fileupload
